trigger:
  none
pr:
  branches:
    include:
      - master
  paths:
    include:
      - model_factory/fridge_obj_det/*
      - model_factory/common/devops/*

parameters:
  - name: exec_environment
    displayName: "Execution Environment"
    default: "prod"
  - name: model_type
    displayName: "type of model to execute"
    default: "fridge_obj_det"
  - name: TARGET_CONDITION
    displayName: "Target Condition for the deployment"
    default: "tags.device='smoke-test-arm'"

variables:
  - group: mlops_platform_${{parameters.exec_environment}}_vg
  - name: PIPELINE_TYPE
    value: ${{parameters.model_type}}

stages:
  # Generate Variables
  - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/variables_template.yml
    parameters:
      exec_environment: ${{parameters.exec_environment}}
      model_type: ${{parameters.model_type}}

  # Run Linting and Unit tests
  - stage: build_validation
    displayName: build_validation
    dependsOn:
      - variable_generation
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/experiment_variables.yml
    jobs:
      - template: build_validation_pipeline.yml
        parameters:
          model_type: ${{ parameters.model_type }}

  - ? ${{ if and(or(eq(variables['Build.Reason'], 'PullRequest'),eq(variables['Build.Reason'], 'Manual')), ne(variables['Build.SourceBranch'], 'refs/heads/master')) }}
    : - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/platform_main_pipeline.yml
        parameters:
          exec_environment: "dev"
          model_type: ${{ parameters.model_type }}
          TARGET_CONDITION: ${{ parameters.TARGET_CONDITION }}

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - stage: build_and_push_to_prod
      dependsOn: 
        - variable_generation
        - build_validation
      variables:
        - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/experiment_variables.yml
      jobs:
        - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/image_generation_semantic_version.yml
          parameters:
            exec_environment: ${{parameters.exec_environment}}
            model_type: ${{parameters.model_type}}
            model_name: "${{parameters.model_type}}_prod_master"
        # push to prod acr
