parameters:
  - name: exec_environment
    displayName: "Execution Environment"
    default: "dev"
  - name: model_type
    displayName: "type of model to execute"
  - name: MODEL_NAME
    displayName: "model name"
    default: $(MODEL_NAME)
steps:
- template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/execute_mlops_pipeline.yml
  parameters:
    script_parameter: |
      python -m ${{ parameters.model_type }}.mlops.src.mlops_pipeline \
        --subscription_id $(SUBSCRIPTION_ID) \
        --resource_group_name $(RESOURCE_GROUP_NAME) \
        --workspace_name $(WORKSPACE_NAME) \
        --cluster_name $(CLUSTER_NAME) \
        --cluster_size $(CLUSTER_SIZE) \
        --cluster_region $(CLUSTER_REGION) \
        --build_reference $(BUILD.BUILDID) \
        --deploy_environment ${{parameters.exec_environment}} \
        --experiment_name $(EXPERIMENT_NAME) \
        --display_name $(DISPLAY_NAME) \
        --wait_for_completion True \
        --environment_name $(ENVIRONMENT_NAME) \
        --env_base_image_name $(ENV_BASE_IMAGE_NAME) \
        --model_name ${{parameters.MODEL_NAME}} \
        --conda_path $(CONDA_PATH)
