parameters:
  - name: exec_environment
    displayName: "Execution Environment"
  - name: use_case_type
    displayName: "type of use case to execute"
  - name: deploy_to_device_target_condition
    displayName: "deployment target device condition"

stages:
  - stage: Build_Edge_Modules
    displayName: Build docker image
    dependsOn:
      - variable_generation
      - build_validation
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/variable_init_for_a_stage.yml
    jobs:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_build_module_e2e_container.yml
        parameters:
          exec_environment: ${{parameters.exec_environment}}
          use_case_type: ${{parameters.use_case_type}}
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_build_module_orch_container.yml
        parameters:
          exec_environment: ${{parameters.exec_environment}}
          use_case_type: ${{parameters.use_case_type}}

    # Generate Deployment manifest
  - stage: Generate_Edge_Deployment_Manifest
    displayName: Generate_Edge_Deployment_Manifest
    dependsOn:
      - variable_generation
      - build_validation
      - Build_Edge_Modules
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/variable_init_for_a_stage.yml
      - name: RTSP_DOCKER_IMAGE_VERSION
        value: "latest"
      - name: ORCHESTRATOR_DOCKER_IMAGE_VERSION
        value: $[ stageDependencies.Build_Edge_Modules.build_orch_docker_image.outputs['orch_image.ORCHESTRATOR_DOCKER_IMAGE_VERSION'] ]
      - name: E2E_DOCKER_IMAGE_VERSION
        value: $[ stageDependencies.Build_Edge_Modules.build_e2e_docker_image.outputs['e2e_image.E2E_DOCKER_IMAGE_VERSION'] ]
    jobs:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_generate_edge_manifest.yml
        parameters:
          use_case_type: ${{parameters.use_case_type}}
          deployment_file_name: "deployment.template.e2e.json"

  - stage: "deploy_iot_edge"
    displayName: "Deploy to IOT Edge"
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/variable_init_for_a_stage.yml
    dependsOn:
      - variable_generation
      - Build_Edge_Modules
      - Generate_Edge_Deployment_Manifest
    jobs:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_edge_deployment.yml
        parameters:
          target_condition: ${{parameters.deploy_to_device_target_condition}}
          deployment_file_name: "deployment.template.e2e.json"

  - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/stage_e2e_test.yml
    parameters:
      exec_environment: ${{parameters.exec_environment}}
      use_case_type: ${{parameters.use_case_type}}
      deploy_to_device_target_condition: ${{parameters.deploy_to_device_target_condition}}
