name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas
    - scikit-learn==1.2.0
    - mlflow==2.1.1
    - azureml-mlflow==1.48.0
    - mldesigner==0.1.0b4
    - azure-ai-ml==1.4.0
    - azure-identity==1.11.0
    - opencensus==0.11.0
    - opencensus.ext.azure==1.1.7
    - opencensus-ext-logging==0.1.1
    - azure-keyvault-secrets==4.6.0
