trigger:
  branches:
    include:
      - master
  paths:
    include:
      - use_case_builder/fridge_detection/*
      - use_case_builder/common/*

parameters:
  - name: exec_environment
    displayName: "Execution Environment"
    default: "prod"
  - name: use_case_type
    displayName: "type of use case to execute"
    default: "fridge_detection"

variables:
- group: mlops_platform_${{parameters.exec_environment}}_vg
- name: PIPELINE_TYPE
  value: ${{parameters.use_case_type}}
    
stages: 
  - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/stage_variable_generation.yml
    parameters:
      exec_environment: ${{parameters.exec_environment}}
      use_case_type: ${{parameters.use_case_type}}
  
  - stage: Build_Edge_Modules
    displayName: Build docker image
    dependsOn:
      - variable_generation
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/variable_init_for_a_stage.yml
    jobs:   
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_build_module_e2e_container.yml
        parameters:
          exec_environment: ${{parameters.exec_environment}}
          use_case_type: ${{parameters.use_case_type}}
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_build_module_orch_container.yml
        parameters:
          exec_environment: ${{parameters.exec_environment}}
          use_case_type: ${{parameters.use_case_type}}
  
  - stage: Generate_Edge_Deployment_Manifest
    displayName: Generate_Edge_Deployment_Manifest
    dependsOn:
      - variable_generation
      - Build_Edge_Modules
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/variable_init_for_a_stage.yml
      - name: RTSP_DOCKER_IMAGE_VERSION
        value: "latest"
      - name: ORCHESTRATOR_DOCKER_IMAGE_VERSION
        value: $[ stageDependencies.Build_Edge_Modules.build_orch_docker_image.outputs['orch_image.ORCHESTRATOR_SEMANTIC_VERSION'] ]
    jobs:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/use_case_builder/common/devops/templates/job_generate_edge_manifest.yml
        parameters:
          use_case_type: ${{parameters.use_case_type}}
          deployment_file_name: "deployment.template.json"
