pr: none
trigger:
  branches:
   include:
     - master
  paths:
    include:
      - devops/*
      - mlops/common/*
      - mlops/london_taxi/*
      - src/london_src/*
      - model/london_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg
- name: PIPELINE_TYPE
  value: london_taxi

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "type of model to execute"
   default: "london_taxi"

stages:
  - template: templates/variables_template.yml
    parameters:
      env_name: ${{parameters.env_name}}
      model_type: ${{parameters.model_type}}
  - template: platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}