pr: none
trigger:
  branches:
   include:
     - master
  paths:
    include:
      - devops/*
      - mlops/common/*
      - mlops/london_taxi/*
      - src/london_src/*
      - model/london_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: MLOps-london_taxi-DEV-VG
- name: PIPELINE_TYPE
  value: london_taxi

stages:
  - template: platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: "dev"
      model_type: "london_taxi"