pr: none
trigger:
  branches:
   include:
     - master
  paths:
    include:
      - devops/*
      - mlops/common/*
      - mlops/nyc_taxi/*
      - src/nyc_src/*
      - model/nyc_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: MLOps-nyc_taxi-DEV-VG
- name: PIPELINE_TYPE
  value: nyc_taxi

stages:
  - template: platform_ci_dev_pipeline.yml
    parameters:
      exec_environment: "dev"
      model_type: "nyc_taxi"