trigger: none
pr: none

parameters:
  - name: exec_environment
    displayName: "Execution Environment"
    default: "prod"
  - name: model_type
    displayName: "type of model to execute"
    default: "nyc_taxi"
  - name: image_version
    displayName: "Build ID/Image version to test"
  - name: TARGET_CONDITION
    displayName: "Target Condition for the deployment"
    default: "tags.device='smoke-test'"

variables:
  - group: mlops_platform_${{parameters.exec_environment}}_vg
  - name: PIPELINE_TYPE
    value: ${{parameters.model_type}}

stages:
  # Generate Variables
  - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/variables_template.yml
    parameters:
      exec_environment: ${{parameters.exec_environment}}
      model_type: ${{parameters.model_type}}

  - stage: Generate_Edge_Deployment_Manifest
    displayName: Generate_Edge_Deployment_Manifest
    dependsOn:
      - variable_generation
    variables:
      - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/experiment_variables.yml
    jobs: 
      - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/generate_deployment_manifest.yml
        parameters:
          exec_environment: ${{ parameters.exec_environment }}
          model_type: ${{ parameters.model_type }}
          image_version: ${{ parameters.image_version }}

  - stage: Deploy_IoT_Edge
    displayName: "Deploy_IoT_Edge"
    variables: 
      - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/experiment_variables.yml
    dependsOn:
      - variable_generation
      - Generate_Edge_Deployment_Manifest
    jobs: 
      - template: ${{variables['System.DefaultWorkingDirectory']}}/model_factory/common/devops/templates/smoke_test.yml
        parameters:
          exec_environment: ${{ parameters.exec_environment }}
          model_type: ${{ parameters.model_type }}
          deployment_id: $(Build.Buildid)
          TARGET_CONDITION: ${{ parameters.TARGET_CONDITION }}