name: fridge-object-detection
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - onnx==1.14.0
    - onnxconverter-common==1.13.0
    - onnxruntime-gpu==1.15.0
    - typer==0.9.0
    - scikit-learn==1.2.0
    - mlflow==2.3.2
    - azureml-mlflow==1.50.0
    - azure-ai-ml==1.7.2
    - azure-identity==1.13.0
    - typer==0.9.0
    - numpy==1.24.2
    - pillow==9.5.0
    - torch==2.0.1
    - torchmetrics==0.11.4
    - torchvision==0.15.2
    - mltable==1.3.0
    - pandas==2.0.0
    - azure-keyvault-secrets==4.7.0
