jobs:
- job: WaitForCallback
  pool: server
  timeoutInMinutes: 0
  dependsOn: Execute_Job_Pipeline
  variables:
    - name: run_name_from_submit_job
      value:  $[ dependencies.Execute_Job_Pipeline.outputs['read_run_id.RUN_NAME'] ] 

  steps:
  - task: AzureMLJobWaitTask@0
    inputs:
      serviceConnection: $(AZURE_RM_SVC_CONNECTION)
      resourceGroupName: $(RESOURCE_GROUP_NAME)
      azureMLWorkspaceName: $(WORKSPACE_NAME)
      azureMLWorkspaceLocation: $(CLUSTER_REGION)
      azureMLJobName: $(run_name_from_submit_job)


